Repository googleapis/nodejs-bigquery-data-transfer, pull requests merged in 2019-05, with the labels that each got.

#193 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#194 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#195 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#197 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
Labels: cla: yes

#198 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#199 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#190 chore: alphabetize template methods
  src/v1/data_transfer_service_client.js
  synth.metadata
Labels: :rotating_light:, cla: yes

#200 build: only push to codecov with Node 10
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#201 fix: DEADLINE_EXCEEDED is no longer retried
  src/v1/data_transfer_service_client_config.json
  synth.metadata
Labels: cla: yes

#203 fix: DEADLINE_EXCEEDED retry code is idempotent
  src/v1/data_transfer_service_client_config.json
  synth.metadata
Labels: cla: yes

#204 refactor: use repo-metadata to generate readme
  .cloud-repo-tools.json
  .gitignore
  .repo-metadata.json
  README.md
  package.json
  samples/README.md
  samples/package.json
  samples/quickstart.js
  samples/test/.eslintrc.yml
  samples/test/quickstart.test.js
  synth.metadata
Labels: cla: yes

#205 docs: update readme to match quickstart
  README.md
  synth.metadata
Labels: cla: yes

#207 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#211 chore: release 1.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#213 refactor: drop dependency on lodash.merge and update links
  package.json
  src/v1/data_transfer_service_client.js
  synth.metadata
Labels: cla: yes

#214 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#215 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#216 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#217 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes
