Repository googleapis/nodejs-bigquery-data-transfer, pull requests merged in 2020-07, with the labels that each got.

#371 build: use bazel build
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#372 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#374 fix: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#377 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#378 chore: update generated protos.js
  protos/protos.js
  synth.metadata
Labels: cla: yes, context: none

#379 build: missing closing paren in publish script
  .kokoro/publish.sh
  synth.metadata
Labels: cla: yes, context: partial

#383 chore: add config files for cloud-rad for node.js, delete Node 8 templates
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#382 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes, context: none

#384 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#385 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#386 build: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: cla: yes, context: full

#387 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#388 build: update protos
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none

#389 docs: add links to the CHANGELOG from the README.md for Java and Node
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: full
