Repository googleapis/nodejs-bigquery-data-transfer, pull requests merged in 2020-11, with the labels that each got.

#411 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: bigquerydatatransfer, automerge, cla: yes, context: full

#413 fix: do not modify options object, use defaultScopes
  package.json
  src/index.ts
  src/v1/data_transfer_service_client.ts
  synth.metadata
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: bigquerydatatransfer, automerge, cla: yes

#416 fix(browser): check for fetch on window
  protos/protos.json
  src/v1/data_transfer_service_client.ts
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: none

#417 build: stop tracking generated files
  src/v1/data_transfer_service_client.ts
  synth.metadata
Labels: api: bigquerydatatransfer, cla: yes, context: none

#418 docs: spelling correction for "targetting"
  README.md
  synth.metadata
Labels: api: bigquerydatatransfer, automerge, cla: yes, context: full
